version: "3"

services:

  traefik:
    container_name: traefik
    image: traefik:v3.2.3
    command:
      - "--log.level=DEBUG"
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik
    depends_on:
      - content-service


  content-service:
    container_name: content-service
    build:
      context: .
      dockerfile: deployments/docker/content-service.dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.content-service.entrypoints=web
      - traefik.http.routers.content-service.rule=Host(`localhost`)
      - traefik.http.services.content-service.loadbalancer.healthcheck.path=/health
      - traefik.http.services.content-service.loadbalancer.healthcheck.interval=10s
      - traefik.http.services.content-service.loadbalancer.healthcheck.timeout=3s
      - traefik.http.services.content-service.loadbalancer.server.port=8010
    environment:
      PORT: ${CONTENT_SERVICE_WEB_PORT}
      GRPC_PORT: ${CONTENT_SERVICE_GRPC_PORT}
      GRACEFUL_TIMEOUT: ${SERVICES_GRACEFUL_TIMEOUT}
    expose:
      - ${CONTENT_SERVICE_WEB_PORT}
    ports:
      - ${CONTENT_SERVICE_WEB_PORT}:${CONTENT_SERVICE_WEB_PORT}
    networks:
      - traefik
      - default

networks:
  traefik:
  default: