version: "3"

services:

  kong:
    container_name: kong
    image: kong:3.8.0
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8443:8443" # Proxy (SSL)
      - "8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE: "off" # DB-less mode
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
    volumes:
        - ./configs/kong.yml:/kong/kong.yml


  content-service:
    container_name: content-service
    build:
      context: .
      dockerfile: deployments/docker/content-service.dockerfile
    environment:
      PORT: ${CONTENT_SERVICE_WEB_PORT}
      GRPC_PORT: ${CONTENT_SERVICE_GRPC_PORT}
      GRACEFUL_TIMEOUT: ${SERVICES_GRACEFUL_TIMEOUT}
    expose:
      - ${CONTENT_SERVICE_WEB_PORT}
    ports:
      - ${CONTENT_SERVICE_WEB_PORT}:${CONTENT_SERVICE_WEB_PORT}
    networks:
      - kong
      - default

networks:
  kong:
  default: