global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

log:
  level: DEBUG